name: Release

on:
  push:
    tags:
      - '*-release'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
    - uses: dtolnay/rust-toolchain@stable

    - name: Check rust version
      run: rustc --version --verbose
    
    - name: Execute release script
      run: |
        chmod +x release.sh
        ./release.sh
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: release-pkg.zip