name: Release

on:
  push:
    tags:
      - '*-release'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
    - uses: dtolnay/rust-toolchain@stable

    - name: Check rust version
      run: rustc --version --verbose
    
    - name: Execute release script
      run: |
        chmod +x release.sh
        ./release.sh
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: release-pkg.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}
            
            This release contains pre-built binaries for multiple architectures.
            
            ### Contents
            - guest-test binaries for x86_64 and aarch64 architectures
            
            ### Installation
            1. Download the `release-pkg.zip` file
            2. Extract the archive
            3. Use the appropriate binary for your architecture